// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SubhadraSolutions.Utils.Data.EntityFramework.SqlServer.DbContexts.Audit;

[Table("AuditLog", Schema = "qfl")]
public partial class AuditLog
{
    [Key]
    public Guid AuditLogID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EventDatePST { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string EventType { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string TableName { get; set; }

    [Required]
    [StringLength(200)]
    public string RecordID { get; set; }

    public string ChangedColumns { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }
}