//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubhadraSolutions.Utils.Compression.Cab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubhadraSolutions.Utils.Compression.Cab.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {1}.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error creating cabinet..
        /// </summary>
        internal static string _1000 {
            get {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure opening file to be stored in cabinet..
        /// </summary>
        internal static string _1001 {
            get {
                return ResourceManager.GetString("1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure reading file to be stored in cabinet..
        /// </summary>
        internal static string _1002 {
            get {
                return ResourceManager.GetString("1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not allocate enough memory to create cabinet..
        /// </summary>
        internal static string _1003 {
            get {
                return ResourceManager.GetString("1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a temporary file..
        /// </summary>
        internal static string _1004 {
            get {
                return ResourceManager.GetString("1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown compression type..
        /// </summary>
        internal static string _1005 {
            get {
                return ResourceManager.GetString("1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create cabinet file..
        /// </summary>
        internal static string _1006 {
            get {
                return ResourceManager.GetString("1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client requested abort..
        /// </summary>
        internal static string _1007 {
            get {
                return ResourceManager.GetString("1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure compressing data..
        /// </summary>
        internal static string _1008 {
            get {
                return ResourceManager.GetString("1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error extracting cabinet..
        /// </summary>
        internal static string _2000 {
            get {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet not found..
        /// </summary>
        internal static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet file does not have the correct format..
        /// </summary>
        internal static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet file has an unknown version number..
        /// </summary>
        internal static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet file is corrupt..
        /// </summary>
        internal static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not allocate enough memory to extract cabinet..
        /// </summary>
        internal static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown compression type in a cabinet folder..
        /// </summary>
        internal static string _2006 {
            get {
                return ResourceManager.GetString("2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure decompressing data from a cabinet file..
        /// </summary>
        internal static string _2007 {
            get {
                return ResourceManager.GetString("2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure writing to target file..
        /// </summary>
        internal static string _2008 {
            get {
                return ResourceManager.GetString("2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinets in a set do not have the same RESERVE sizes..
        /// </summary>
        internal static string _2009 {
            get {
                return ResourceManager.GetString("2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet returned on NEXT_CABINET is incorrect..
        /// </summary>
        internal static string _2010 {
            get {
                return ResourceManager.GetString("2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client requested abort..
        /// </summary>
        internal static string _2011 {
            get {
                return ResourceManager.GetString("2011", resourceCulture);
            }
        }
    }
}
