//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubhadraSolutions.Utils.Linq.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubhadraSolutions.Utils.Linq.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;link href=&quot;https://unpkg.com/treeflex/dist/css/treeflex.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;style&gt;
        ///.example .tf-nc {
        ///  /* css here */
        ///}
        ///
        ///.tf-custom .tf-nc:before,
        ///.tf-custom .tf-nc:after {
        ///  /* css here */
        ///}
        ///
        ///.tf-custom li li:before {
        ///  /* css here */
        ///}
        ///table.tbl {
        ///    font-family: verdana,arial,sans-serif;
        ///    font-size: 11px;
        ///    color: #333333;
        ///    border-width: 1px;
        ///    border-color: #666666;
        ///    border-collapse: collapse;
        ///}
        ///
        ///th.h {
        ///    border-width: 1px;
        ///    padding: 8px;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpressionTreeHtmlPrefix {
            get {
                return ResourceManager.GetString("ExpressionTreeHtmlPrefix", resourceCulture);
            }
        }
    }
}
